title: Tallyist for Android
description: Privacy policy and support for Tallyist, the drink tracker for Android.
url: https://semmes.github.io
baseurl: /TallyistAndroid
plugins: []
exclude:
  - README.md
